### ISSUE TITLE
Mismatch between transitions set-up and executed

### ISSUE THREAD

**Issue by PatTheMav** [exeldro/obs-move-transition#1]
As discussed on Discord, here's my rundown of all transitions and how they (unexpectedly) behave. At first I was about to check in and out transitions separately, but only the movement direction (in/out) changed), the direction stayed the same.

# Zoom Off

Match | Position | Actual
------|----------|--------
✓ | `None` | `None`
✖︎ | `Center` | `Bottom Center`
✖︎ | `Away from Center` | `Top Center`
✖︎ | `Top Left` | `Bottom Left`
✖︎ | `Top Center` | `Bottom Right`
✖︎ | `Top Right` | `Bottom Right`
✖︎ | `Center Right` | `Bottom Right`
✓ | `Bottom Right` | `Bottom Right`
✖︎ | `Bottom Center` | `Bottom Right`
✓ | `Bottom Left | `Bottom Left`
✖︎ | `Center Left` | `Bottom Left`

# Zoom On

Match | Position | Actual
------|----------|--------
✓ | `None` | `Top Left`
✖︎ | `Center` | `Top Left`'ish (see below)
✓ | `Center Right` | `Center Right`
✖︎ | `Bottom Left` | `Center Left`'ish (see below)
✖︎ | `Center Left` | `Bottom Left`

This only contains the differences to the "Zoom off" checks. `Center` and `Bottom Left` are a bit weird:

* Center seems to move "around" the outgoing scene, starting in the center, then moving around it to the left.
* `Bottom Left` seems to come in from the `Center Left`, but slightly lower than actual `Center Left`

**Comment by exeldro** [comment]
Fixed in version 0.0.2
