### ISSUE TITLE
[Feature Request] Audio Move Filter: Have set on/off positions and an audio threshold

### ISSUE THREAD

**Issue by swolekat** [exeldro/obs-move-transition#100]
My use case is that I have a text to speech channel point reward that I would like to be shown when the text to speech is talking but hidden when it is not talking.

I've set up a video showcasing what I'd like to have working https://www.youtube.com/watch?v=A3NSgWepcCg

I'd like to have a bit of a timer after the audio is in the "off" position just in case there is a pause in speaking.

I think this is functionality that a lot of people are looking for but have implemented it in a lot of non obs native ways.

**Comment by exeldro** [comment]
You can have an audio move filter enable an move source filter that moves the source to the correct position and an other combination of audio move and move source to move it out of view again.

**Comment by swolekat** [comment]
What you suggested worked for me. Thanks!
