### ISSUE TITLE
Please, provide a tag or a source tarball to allow packaging

### ISSUE THREAD

**Issue by eribertomota** [exeldro/obs-move-transition#101]
Dear @exeldro,

I am maintaining obs-move-transition in Debian. To package it, I need a tag for each release or a tarball with the source code and the version. Without a tarball or a tag, I will need to discover what was the last commit for the last release. Another problem is without a tag or tarball with version, Debian won't be able to search for new releases to be packaged.

Cheers,

Eriberto

**Comment by exeldro** [comment]
2.5.2 is now tagged and a release on GitHub

**Comment by eribertomota** [comment]
Thanks!

**Comment by eribertomota** [comment]
Could you provide tags for downstream-keyer too? I am trying send it to
Debian.
