### ISSUE TITLE
Flathub deployment

### ISSUE THREAD

**Issue by eaglesemanation** [exeldro/obs-move-transition#104]
Currently there is no "easy" way for users to install this plugin on Linux (by easy I mean through package manager). The most widely adopted package manager that works across multiple distributions is `flatpak` and the biggest repository for it is [Flathub](https://flathub.org), which already includes multiple plugins such as [SceneSwitcher](https://github.com/flathub/com.obsproject.Studio.Plugin.SceneSwitcher) and [InputOverlay](https://github.com/flathub/com.obsproject.Studio.Plugin.InputOverlay). I wanted to work on publishing this plugin as well, I just wanted to ask if you are interested in doing that, or at least ok with me publishing it myself? All I need for it to work is to make a [few changes to build system](https://github.com/exeldro/obs-move-transition/compare/master...eaglesemanation:out-of-tree).

**Comment by exeldro** [comment]
I am interested in my plugins being available to more users. If it works good for this plugin I'm interested to get it for my other OBS plugins too.

**Comment by eaglesemanation** [comment]
I've done the most basic testing, and it seems to work fine. Specifically, I saw "Move" transition appear as an available option, and I don't see reasons for anything else to be broken.

There is a simple guide on deploying apps to Flathub: https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app. TLDR: new pull request needs to be created with manifest file. If you want to take ownership of deployments, you'll need to do it yourself, because I can't find any documentation on transferring repository without administration involvement. There are all configuration files that I used to build the plugin on my machine: https://gist.github.com/eaglesemanation/6d73e38f17250ab73cfb86e72c4ddb72

**Comment by exeldro** [comment]
the configuration you used points to the 2.5.2 tag and commit, but those don't contain the merged required changes shouldn't that point to the latest master commit in com.obsproject.Studio.Plugin.MoveTransition.yaml?

**Comment by eaglesemanation** [comment]
It's possible to remove `tag` and point to the latest master branch commit, but that will also require to remove `x-checker-data`, otherwise flathubbot will override it. I feel the best solution would be to create new minor release `2.5.3` with merges applied.

**Comment by exeldro** [comment]
I bumped the version to 2.5.3 and made the pull request
https://github.com/flathub/flathub/pull/2697

**Comment by eaglesemanation** [comment]
Plugin was published to Flathub successfully, now it's listed as a plugin for OBS

![Screenshot from 2021-12-28 18-35-11](https://user-images.githubusercontent.com/52473614/147614805-9487a56f-b324-4466-96db-406e9e142639.png)

Thank you for helping with this! If you want to publish any other plugin - feel free to open an issue and mention me there, I'll work on manifests for it and test it.
