### ISSUE TITLE
Move transition ignores compositing mode

### ISSUE THREAD

**Issue by matiaspl** [exeldro/obs-move-transition#115]
When a source has non-default compositing mode enabled, for the duration of transition it is always changed to "Normal".

**Comment by exeldro** [comment]
Here is a first test version with blend mode support:
https://github.com/exeldro/obs-move-transition/actions/runs/2035909652

**Comment by matiaspl** [comment]
Works fine for me!

**Comment by jamealg** [comment]
Is there somewhere else I can download this or do you have a copy saved @matiaspl? It doesn't look like this has been released yet and the download in the provided link has expired.

**Comment by exeldro** [comment]
This one should work for now:
https://github.com/exeldro/obs-move-transition/actions/runs/2269653804

Will make it a release soon.

**Comment by jamealg** [comment]
Thanks @exeldro this works wonderfully.

**Comment by exeldro** [comment]
released in version 2.6.0
