### ISSUE TITLE
Problem with fade effect

### ISSUE THREAD

**Issue by jmaciej7** [exeldro/obs-move-transition#12]
Hi!
There is a problem with fade transition in connection with appearing or disappering items. 
When some source wasn't in the previous scene somtimes first it suddenly appears and then gently fades in (transition 1, 3, 5). 
Sometimes sources don't fade out (transition 2 - background)

Video showing described problem:
[Video](https://1drv.ms/v/s!AvuDbMfgedMFg9Juf_MFyvAe2QSuug?e=gAZ2Rv)

**Comment by exeldro** [comment]
Which version of the plugin is used?
Have you set easing for the fade effects?
You have set the fade something like this?
![image](https://user-images.githubusercontent.com/5457024/80029105-8eb82a00-84e6-11ea-953a-1cfccb3d4f0a.png)

**Comment by jmaciej7** [comment]
> Which version of the plugin is used?
1.1.2

> Have you set easing for the fade effects?
Yes, but without easing behaviour is the same.

> You have set the fade something like this?
Yes. Both for appearing and disappearing items.

**Comment by exeldro** [comment]
I have an idea what might cause this, I will try and fix it tomorrow.

**Comment by exeldro** [comment]
Should be fixed in version 1.1.3

**Comment by jmaciej7** [comment]
Now it works much better. 
Thank you for your immediate reaction.
