### ISSUE TITLE
Move action loses target source after restart

### ISSUE THREAD

**Issue by Moxinilian** [exeldro/obs-move-transition#125]
# Tested on

OS: Arch Linux
OBS: 27.2.4-2
Move Transition: 2.6.1

# Steps to reproduce

Add a Move action to a scene that triggers a Move value on a source of that scene. Quit OBS. Re-open OBS and click the start button on the Move action to trigger the Move value.

# Expected behavior

The Move value should be triggered.

# Observed behavior

The Move value is not triggered. Re-setting the target Move value in the Move action then pressing the start button resolves the issue until the next restart (but that is not a good long term fix, especially in big scenes).

# Notes

Thanks for the awesome plugin. If you need any more details on how to reproduce this bug, I am available!

**Comment by exeldro** [comment]
this is fixed by https://github.com/exeldro/obs-move-transition/commit/2b0752643e687316928f953fd8fe715674543d43 which is not released yet. You can download the test version here: https://github.com/exeldro/obs-move-transition/actions/runs/3183813275
