### ISSUE TITLE
Apple silicon support

### ISSUE THREAD

**Issue by montyclt** [exeldro/obs-move-transition#126]
OBS 28 beta introduces Apple Silicon support, but plugins need to be updated.

**Comment by exeldro** [comment]
yeah, can you help me with that?

**Comment by montyclt** [comment]
> yeah, can you help me with that?

Of course. I can try to build it from my Apple Silicon MacBook from source code. There are any build instruction?

**Comment by 3laws** [comment]
Dropping in to see if you need help with overall 28.0.0 support. I don't see the plugin in the flatpak `beta` branch.

**Comment by exeldro** [comment]
The current and old versions of the move transition plugin should work fine on OBS 28, because move transition is not linked to Qt which updated with OBS 28. 
Only Apple Silicon was not supported before. I got it working for my other plugins, so I should be able to get it working for move transition in the coming week.

**Comment by petaren** [comment]
I'm on an M1 mac and tried building it according to the OBS instructions and the move-transition instructions. I then tried to copy the `move-transition.plugin` file to the `~/Library/Application Support/obs-studio/plugins` directory. But I'm not seeing it in OBS. I also tried to copy it into the `OBS.app/Contents/Plugins` directory with no luck. 

Is there anything else that needs to be done?

**Comment by DuncanHills** [comment]
I can help troubleshoot the build process. I am on arm64 version 28.0.1 of OBS. I have actually never used move-transition before, but I really want to try it for manipulating paramter values in OBS. @petaren do you have more detailed build instructions for this plugin on M1?

**Comment by DuncanHills** [comment]
> The current and old versions of the move transition plugin should work fine on OBS 28, because move transition is not linked to Qt which updated with OBS 28. Only Apple Silicon was not supported before. I got it working for my other plugins, so I should be able to get it working for move transition in the coming week.

I found an older version of the plugin (2.5.2) that another user built for Apple silicon [in this OBS Forum thread](https://obsproject.com/forum/threads/obs-on-apple-silicon.133606/post-550520). However, it generated the following error referencing QT5 in the logs on startup:

```
os_dlopen(/Users/adam/Library/Application Support/obs-studio/plugins/move-transition.plugin/Contents/MacOS/move-transition->/Users/adam/Library/Application Support/obs-studio/plugins/move-transition.plugin/Contents/MacOS/move-transition): dlopen(/Users/adam/Library/Application Support/obs-studio/plugins/move-transition.plugin/Contents/MacOS/move-transition, 0x0101): Library not loaded: @executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Users/adam/Library/Application Support/obs-studio/plugins/move-transition.plugin/Contents/MacOS/move-transition
  Reason: tried: '/Applications/OBS.app/Contents/MacOS/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets' (no such file), '/System/Library/Frameworks/QtWidgets.framework/Versions/5/QtWidgets' (no such file)
```

**Comment by petaren** [comment]
@DuncanHills I followed the instructions to build OBS on their website. But I see now that the instructions seem to have been removed.

These are the steps I followed:
1. `git clone --recursive https://github.com/obsproject/obs-studio.git`
2. `cd obs-studio/CI`
3. `./build-macos.sh`

To build the move-transition, I followed the instructions in the readme:
https://github.com/exeldro/obs-move-transition

But, basically:
1. Clone the repo to the `obs-studio/plugins` directory
2. Rename folder: `mv obs-move-transition move-transition` (not sure if this is important)
3. Add `add_subdirectory(move-transition)` to `plugins/CMakeLists.txt`
4. Rebuild OBS

**Comment by thomaslfessler** [comment]
Building for Arm64 with the -arch arm64 option.
  
./build-macos.sh --skip-dependency-checks -a arm64

Now, if building OBS for Arm64 would be as easy as above, I would have completed it hours ago.  Could the github pipeline build process for Arm64 somehow be different than what's in the repo, I'm currently blocked with   

"_sws_setColorspaceDetails", referenced from:
      _video_scaler_create in video-scaler-ffmpeg.c.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[164/1316] Building C object plugins/obs-x264/CMakeFiles/obs-x264.dir/obs-x264.c.o
ninja: build stopped: subcommand failed.

I'm currently building ffmpeg-apple-arm64 build as it seems the usual flavor of the ffmpeg libs are not arm64 variants.  So far it's compiling without any issues.

Any thoughts?

**Comment by exeldro** [comment]
It is now available for download on the OBS forum

**Comment by montyclt** [comment]
Tested and working on my MBP M1. Thank you!
