### ISSUE TITLE
Transition scene when it gets embedded

### ISSUE THREAD

**Issue by sorenh** [exeldro/obs-move-transition#13]
I have a scene (let's call it SceneA) with a webcam source and some text and stuff. Then I have another scene, SceneB, which uses SceneA as a source in one corner. It would be awesome if your plugin could handle that the switch from SceneA to SceneB so SceneA would shrink into the corner. Does that make sense?

**Comment by sorenh** [comment]
Right now I'm doing it by having an intermediate Scene which consists simply of SceneA embedded in it. When I switch to SceneB, it transitions in the expected way, but that seems suboptimal.

**Comment by exeldro** [comment]
The way you do it now is the most efficient way I can think of at the moment. An other solution is instead of using a shrinked version of SceneA in SceneB, using the sources of SceneA shrinked in SceneB.

**Comment by exeldro** [comment]
This should now work with version 1.2.2
