### ISSUE TITLE
Move Transition not recognized in OBS Studio 

### ISSUE THREAD

**Issue by Buddy-T** [exeldro/obs-move-transition#132]
Installing Move Transition in OBS 27.2.4 and it will not appear in the scene transition section. I have installed V28 with the latest V of MT to no avail.  I have used the Windows install package and have also used the zip files placing them in the directories. Any Ideas would be greatly appreciated.

Windows 11
OBS 27.2.4
Move Transition 2.6.4 

Thanks

Buddy T

**Comment by exeldro** [comment]
for obs 27 use move transition 2.6.1 or lower

**Comment by Buddy-T** [comment]
Thanks. Inactuall made it work on 28. I tried the 2.7.1 on 27 but could not make it work. The + is not in scenes on 27. Maybe try a lower version?

I need 27 until NDI works 9n 28.

Thank you for the quick response.



Buddy

On Oct 11, 2022, at 11:50 AM, Exeldro ***@***.***> wrote:

﻿

for obs 27 use move transition 2.6.1 or lower
