### ISSUE TITLE
Move Value - 2 Filters active makes OBS freak out on CPU usage

### ISSUE THREAD

**Issue by OtterNas3** [exeldro/obs-move-transition#137]
Hey there!

OBS Version used: 27.2.4 (For various reasons i cant update to 28.x yet)
Plugin version: 2.6.1
Normal CPU usage: 1-3% reported by OBS

Setup:
I have 2 "Move Value" Filters on each of my Audio sources
"Off" Fades the Volume in 3 seconds to 0%
"Reset" Fades the Volume in 3 seconds back to the normal level

If i enable one of them at a time it fades normal, CPU usage stays at 1-2% in OBS after the move.
But if "Off" or "Reset"  is still running, and i enable the counter part Filter at the same time, CPU usage jumps up to 9-13% and stays there even after both Filters are completed and they disable themself again.

Any "Move Source" or "Move Value" behaves really choppy after this, if it does anything at all anymore.
Only disabling the "effected" source and reactivate it, will fix the occured behaviour.

Here is a Video to show what i mean:
https://drive.google.com/file/d/1npY5bNmcugp3grtp8rHJA8P_R8QIJAfY/view?usp=sharing

**Comment by exeldro** [comment]
That is a bug in the audio monitor plugin, will try and fix that and post it here too.

**Comment by exeldro** [comment]
This should be fixed with Audio Monitor version 0.8.2
