### ISSUE TITLE
Hotkey Crashes OBS

### ISSUE THREAD

**Issue by JadeNeoma** [exeldro/obs-move-transition#141]
OBS Crashes if I use a hotkey (Ctrl-Alt-B) to zoom. Specifically, it crashes when I use the hotkey to disable the filter which prompts it to reverse the move. This is using Move Source as a Filter on the scene moving a folder which contains two nested scenes. I can't think of a workaround but I don't understand why the hotkey crashes it when disabling the filter doesn't

**Comment by exeldro** [comment]
Do you have an OBS crash log for me to look at?

**Comment by exeldro** [comment]
Tried to replicate it without success. What version of the Move plugin?
I notice the crash log metions streamelements, is it only on the streamelements version of OBS?

**Comment by JadeNeoma** [comment]
Afaik there isn't a stream elements version of OBS stream elements is just another plugin. StreamLabs has its own OBS derivative but Stream Elements is just a plugin

**Comment by JadeNeoma** [comment]
I can try disabling the plugin and seeing if it still breaks

**Comment by JadeNeoma** [comment]
[Move Transition] loaded version 2.6.1

**Comment by JadeNeoma** [comment]
I've just updated and it doesn't seem to. I apologise, I thought I was already on the latest version

**Comment by JadeNeoma** [comment]
Thanks for the help

**Comment by exeldro** [comment]
You can follow updates in the [github releases](https://github.com/exeldro/obs-move-transition/releases) or on the OBS forum [resources page](https://obsproject.com/forum/resources/move-transition.913/updates) or follow [my twitter](https://twitter.com/exeldro)
