### ISSUE TITLE
Instant duration for Move filters

### ISSUE THREAD

**Issue by DeMineArchiver** [exeldro/obs-move-transition#142]
Setting duration to **0ms** for **Move Value / Action / etc.** filter would be great, but the minimum **duration override is 10ms**. 

> I think there was **no point** in making **this limitation**. I hope it will be fixed in a future update.

![Custom Duration 10ms](https://i.imgur.com/gWtXbZA.png "Custom Duration Screenshot")

**Comment by exeldro** [comment]
The reason a minimum was added is that the move is done divided over time, but you can not divide by 0.
I might be able to do some extra checks to prevent that.

**Comment by DeMineArchiver** [comment]
> The reason a minimum was added is that the move is done divided over time, but you can not divide by 0.
> I might be able to do some extra checks to prevent that.

That would be amazing to implement! Thanks!

**Comment by exeldro** [comment]
Here is a test version with duration 0 allowed:
https://github.com/exeldro/obs-move-transition/actions/runs/3775147792
