### ISSUE TITLE
[Bug] Move Source only saves X/Y position changes to 1 decimal point

### ISSUE THREAD

**Issue by ZombieHDGaming** [exeldro/obs-move-transition#149]
Hello!
Currently I am trying to work on a zoom capability for my streams, however, in my current setup we are attempting to move by 1.25 times in a specific direction:

`pos: x+0.0 y*1.25 rot:+0.0 scale: x*1.000 y*1.000 crop: l+0 t+0 r+0 b+0`

This transform would move the source up, which does work as intended while OBS Studio, but if OBS Studio shuts down, the filter gets adjusted to now cut off the 5, as shown below:

`pos: x+0.0 y*1.2 rot:+0.0 scale: x*1.000 y*1.000 crop: l+0 t+0 r+0 b+0`

I was wondering if it would be possible to make saving for more than 1 decimal point possible, as currently we'd have to update the filters each time we open OBS to make it hold the 5 we need for everything to line up.

I can also provide my other filter transform codes to help if needed!

**Comment by exeldro** [comment]
workaround instead of `*1.25` you can use `/0.8`
