### ISSUE TITLE
Move Action Crashing OBS

### ISSUE THREAD

**Issue by blushell** [exeldro/obs-move-transition#153]
When I try to use move action it will sometimes work once then crash obs. most of the time though it just crashes obs.
Source Keycam overlay is a group
[Crash 2023-03-20 15-55-03.txt](https://github.com/exeldro/obs-move-transition/files/11022570/Crash.2023-03-20.15-55-03.txt)
![obs64_zOYf62ecrB](https://user-images.githubusercontent.com/3621606/226452258-c5793ce9-9988-43f2-9baa-b6ebf8fd8549.png)

**Comment by exeldro** [comment]
Made a fix https://github.com/exeldro/obs-move-transition/commit/bb2ab4f9533b94e8d32367e306ae26c5085cdf09

Can you test if this build works for you: https://github.com/exeldro/obs-move-transition/actions/runs/4476270579

**Comment by blushell** [comment]
Seems to be fixed! will update if I come across anymore issues. Thanks!

**Comment by exeldro** [comment]
Version 2.8.3 with the fix is out now
