### ISSUE TITLE
Incorrect depth for appearing elements

### ISSUE THREAD

**Issue by Cykelero** [exeldro/obs-move-transition#16]
# Bug summary

A z-ordering issue occurs for appearing elements, when transitioning to a scene with three or more appearing elements.

![move-z-bug](https://user-images.githubusercontent.com/2979318/80135174-262d8380-85a0-11ea-9a53-6bafc6c68d51.gif)

# Details

When transitioning from a scene with a single element D; to a scene with four elements A, B, C and D; during the transition, C is incorrectly displayed over D, instead of under.
A and B are displayed at the correct depths.

# Reproduction

Here is the smallest reproduction case I could make, seen in the GIF above: 
[move-z-bug.json.zip](https://github.com/exeldro/obs-move-transition/files/4524465/move-z-bug.json.zip)

**Comment by exeldro** [comment]
At the moment it takes the average depth times 2 (to make it an integer) of the sources so in your example:
Red: 0 (0*2)
Green: 2 (1*2)
Blue: 4 (2*2)
Yellow: 3 (((3*2)+(0*2))/2)

I could fix your example by taking the starting depths, but that would break other use cases.
The way I made it now works in most cases, but I am always open to suggestions of better ways to handle it.

A work around for this case is to add a couple of hidden sources to scene B to get yellow on the same depth in both scenes.

**Comment by Cykelero** [comment]
Ah, I understand, dealing with depths is way tricker than what it seems!

When deciding on depths, there are two kind of sources: matched sources, and unmatched sources. The matched sources may have the same order in the _from_ scene and _to_ scene, or may have a different order.

I think an important goal of the depth assignment should be to optimize for the case where the order is the same (i.e. ensure their relative depths are preserved): this would give authors more control and predictability.

**Comment by Cykelero** [comment]
Handling the scenario where matched source order is preserved could be done by ensuring their relative order; and redistributing the depths of unmatched sources, maintaining the relative order of unmatched sources to matched ones.

For instance, in this situation:
We're transitioning from Scene 1 to Scene 2.
Scene 1 has sources G, H, **A**, I, **B**, J.
Scene 2 has sources **A**, X, Y, **B**, Z.
The common sources are A and B; the unique sources are G, H, I, J (disappearing) and X, Y (appearing).

We would take these steps:
1. Group unmatched sources. Since matched source order is maintained from one scene to the other, we can define stable groups for the _unmatched_ sources:
    - “unmatched sources before A”: G, H
    - “unmatched sources between A and B”: I, X, Z
    - “unmatched sources after B”: J, Z
2. Depths are distributed in order, alternating unmatched source groups, and matched sources. In our example:
    1. sources before A
    2. A
    3. sources between A and B
    4. B
    5. sources after B

The result would be G, H, **A**, I, X, Y, **B**, J, Z.

This would respect the order of all sources of a given scene between themselves.

In the case where matched sources have a _different_ order between the two scenes:
- it would be OK to use the current algorithm as a satisfying fallback
- or, for future improvement maybe, the program could attempt a best-effort ordering: e.g. if the order of matched sources is _from:_ ABC and _to:_ BCA, the depth decision algorithm above could be run with only A and B considered matched sources, and C being handled like an unmatched one. This would require some kind of way of deciding which sources have their order respected and which do not.

**Comment by exeldro** [comment]
I changed it to starting with the list of items of the starting scene and injecting the items of the ending scene into it.
The injection position starts at 0 and as soon as a matched item is found and its position is larger than the current position it starts injecting after that matched item.

The example in the post above would result in: G, H, A, X, Y, I, B, Z, J

You can download a test version here: 
https://github.com/exeldro/obs-move-transition/actions/runs/86597484

**Comment by Cykelero** [comment]
Smart!
I tried it in a few scenarios and it seems to work well in these :)
