### ISSUE TITLE
Builds for linux

### ISSUE THREAD

**Issue by maxdrash** [exeldro/obs-move-transition#17]
Hello, you make a very good work and appreciated !

Can you provide some builds ready for Linux ? Like Ubuntu 18.04, Ubuntu 20.04 and Debian 10 ?

Thank you !

**Comment by exeldro** [comment]
I think GitHub workflow supports Ubuntu. So that should be possible. It might take awhile because I don't use Linux normally.

**Comment by MichaelTunnell** [comment]
I would love to use this plugin and would happily donate for it because this is a potential game changer for me. Please create support for Linux users. Linux is free to get so if you wouldn't mind downloading a distro to do the builds I'd very much appreciate it and would be happy to donate for the work involved.

**Comment by jay061996** [comment]
I followed the build instructions using https://obsproject.com/wiki/Install-Instructions#linux-portable-mode-all-distros 
I then moved `move-transition.so` 
found at `~/obs-studio-portable/obs-plugins/64bit/move-transition.so`
to `~/.config/obs-studio/plugins/move-transition/bin/64bit/move-transition.so`
as well as all the locale files (`en_US.ini` and such)
found at `~/obs-studio-portable/data/obs-plugins/move-transition/locale/`
to `~/.config/obs-studio/plugins/move-transition/data/locale/`

It appears to work on Linux just fine.

[move-transition-1.2.6-linux.zip](https://github.com/exeldro/obs-move-transition/files/4635733/move-transition-1.2.6-linux.zip)
This is what was built. Install instructions is move `move-transistion` folder to `~/.config/obs-studio/plugins/`

**Comment by exeldro** [comment]
Github [Actions](https://github.com/exeldro/obs-move-transition/actions) now also builds on ubuntu x64. Can you test [that](https://github.com/exeldro/obs-move-transition/suites/686626686/artifacts/6413028) build?

**Comment by jay061996** [comment]
Works for me on Manjaro KDE.

**Comment by MichaelTunnell** [comment]
I don't know what I need to test. I'm a designer and content creator but give me what to test and I'll test it on every major Linux distro! 

I think the GitHub Action is different from the attached zip so not sure what needs to be tested but guide me to the river and II'll go swimming. :D

**Comment by maxdrash** [comment]
It's seem good to me on Ubuntu 20.04.

**Comment by mhfarahmandm** [comment]
I followed steps on a `Raspberry Pi 4` running `Ubuntu 20.10 desktop`
It didn't work :(
The plugin folder on `.config/obs-studio/` didn't exists so I created it.
What can I do?
