### ISSUE TITLE
Add alpha channel support for shaderfilter

### ISSUE THREAD

**Issue by egorovna26** [exeldro/obs-move-transition#172]
obs-shaderfilter 2.0.0 has the ability to edit the alpha channel
![image](https://github.com/exeldro/obs-move-transition/assets/23078561/24867045-1efb-4ffe-b4db-4cf90a4aeaf4)
but move value does not provide such an opportunity
![image](https://github.com/exeldro/obs-move-transition/assets/23078561/88c508c9-e2ee-4b39-bd80-3f580434b985)

**Comment by DeMineArchiver** [comment]
Made a pull request #171
