### ISSUE TITLE
【Issue Report】UI is blocked since of reversed order for requesting lock 

### ISSUE THREAD

**Issue by walker-WSH** [exeldro/obs-move-transition#174]
Hi @exeldro ,   I detected an UI block issue which is caused by obs-move-transition.dll.
Here is my analysis result:

As current logic in obs, `scene->video_mutex` should be requested after `obs->data.sources_mutex`.
If there exist reversed order, the block issue will happen.

It seems you should not invoke `obs_scene_create_private` between `lock(scene->video_mutex)` and `unlock(lock(scene->video_mutex))
`

Please confirm. Thanks~

--------------------------------------------------------------------------------

     
![l_141445122_1767_ada04107b7e09aae63c5c38374a6d67d](https://github.com/exeldro/obs-move-transition/assets/18413354/04008a02-7aa1-478d-a648-330c9fd7f380)

**Comment by exeldro** [comment]
this should be fixed by https://github.com/exeldro/obs-move-transition/commit/752c06b10f7f4dcd5fe184465490abb336ce178f
