### ISSUE TITLE
Little incompatibility with "Source Clone" plugin?

### ISSUE THREAD

**Issue by bitmochibit** [exeldro/obs-move-transition#175]
Hello! Thank you for the fantastic work you're putting into these plugins, it's astonishing.

I'm having a little issue with this plugin. I don't know if I'm doing something wrong, if that's the case I'm sorry.
There are two scenes A and B.

**A Scene**
Webcam (With some move values filters that I control with the move action filters in the current scene)
Blur Effect W. [Source Clone] (with blur effect)

**B Scene**
Webcam (It's the same as the webcam in A)

When the move plugin is transitioning from A->B it works fine.
However, when I transition from B->A, the plugin moves the **Webcam** from source B towards the **Blur Effect W. [Source Clone]**
and then I think the animation completes and "teleports" the webcam to the correct transform of **Webcam** in scene **A**.

I've tried without any filters and the problem still persists (only transitions).

**Comment by exeldro** [comment]
It was indeed a bug that I was able to replicate and fix.
You should be able to get the improved version from the bottom of this page: 
https://github.com/exeldro/obs-move-transition/actions/runs/6183276075
or you can wait for the new release expected later today
