### ISSUE TITLE
OBS problem with non-English characters

### ISSUE THREAD

**Issue by marek7400** [exeldro/obs-move-transition#186]
Unfortunately, the plugin cannot be used with national diacritical marks. It shows a rhombus with a question mark, and then only the proper character.

example of Polish characters:
ą, ć, ę, ń, ó, ś, ź, ż

move-transition-2.9.6-windows+OBS Studio v30.0 (Windows 10)

https://github.com/exeldro/obs-move-transition/assets/149798060/5b2b6eb9-7f47-4cd3-add2-3a0e947381fb

**Comment by exeldro** [comment]
That looks like something that should be easy to fix.

**Comment by exeldro** [comment]
I made a fix, you can test it by downloading the build from the bottom of this page: https://github.com/exeldro/obs-move-transition/actions/runs/7083309431

**Comment by milenamilka755** [comment]
Fixed. Thanks.
