### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by COOLIGUAY** [exeldro/obs-move-transition#19]
Mismatch between:

https://github.com/exeldro/obs-move-transition/blob/667d51ae23d6e73dc695d7de5ca6b4676abd3658/move-transition.c#L1881

and:

https://github.com/exeldro/obs-move-transition/blob/667d51ae23d6e73dc695d7de5ca6b4676abd3658/data/locale/en-US.ini#L48

It should be on both lines "TransitionScaleType" or "ScaleType".

Translations of that text are not shown.

![image](https://user-images.githubusercontent.com/55640387/80762721-6317ee00-8b3d-11ea-9e0c-58425a9fd338.png)

**Comment by exeldro** [comment]
Fixed with 9fcf417d89981f68f6275d8ea9fbdc2d3cf9b98c

**Comment by exeldro** [comment]
Released with version 1.2.4
