### ISSUE TITLE
incorrect work NVIDIA AR Move

### ISSUE THREAD

**Issue by Kasseopey** [exeldro/obs-move-transition#190]
Hi!

If I create new filtre "NVIDIA AR Move", and select Action "move source" - i can't select property "Crop right". It automaticly changed to "Crop top" ... but work as "Crop right". And yes - "Crop top" is doesent work

NVIDIA SDK - fresh, today updated
OBS 30.0.2 clean portable
Move 2.9.7

**Comment by exeldro** [comment]
that is indeed a bug. I made a fix, you can download the test build from the bottom of this page:
https://github.com/exeldro/obs-move-transition/actions/runs/7336240667

**Comment by Kasseopey** [comment]
Yes, now work corectly, thank you!
