### ISSUE TITLE
Text source positional/alignment 'popping' when text content is changed while not on screen (studio mode off)

### ISSUE THREAD

**Issue by GrandyB** [exeldro/obs-move-transition#195]
Been happening for as long as I can remember with the move transition when not in studio mode.
Has been the source of many headaches over the years!

Steps are like this:
1. Text source is shown with the name of a caster (centred in bounding box)
2. We move into game scene, caster name is not on the game scene
3. We use an external tool to update the caster's name to something shorter or longer
4. We switch back to the scene with the text in it

At this point, it doesn't handle the new text content very well during transition, then self-corrects once the transition ends... moves into place with incorrect alignment, then 'pops' into correct alignment after transition ends. If I were to guess, the move transition uses the text size it last knew to decide how to reposition the text source, and then once it's in its correct position, then updates the text within its bounding box.

One hack I did find a while ago is that if, between steps 3 and 4, I toggle studio mode briefly with the caster's scene then in preview, then toggle studio mode off, the text updates in the preview window and then the move transition acts as it should.

So what I think (?) I'm basically asking for is for this text update to somehow be done pre-transition; maybe detect if there's text sources and pre-render somehow.

I appreciate this could be more of an OBS issue than a move transition one, but all inbuilt transition types seem to handle this scenario fine so perhaps there is something to be said for it.

Many thanks.

**Comment by exeldro** [comment]
Thank you reporting the issue.
I am able to replicate the issue and will look into fixing it.

**Comment by exeldro** [comment]
I made a fix. Can you test if the build at the bottom of [this page](https://github.com/exeldro/obs-move-transition/actions/runs/7834018655) fixes it for you?

**Comment by GrandyB** [comment]
It does appear to solve the issue :)

Tried with bounding boxes, changing the underlying text, transitioning back in - it appears without the previous jitter after motion.

Also tried without bounding boxes, and just used a transform alignment = top centre, which I recall having problems with a while ago when I last tried it, and that appears to work as intended too.
