### ISSUE TITLE
Move Video Capture Device doesn't work on versions over 2.8.2

### ISSUE THREAD

**Issue by adrienmenielle** [exeldro/obs-move-transition#197]
Hi! I use the Move plugin to control my PTZ cam (an Insta360 Link). My problem is, Move Video Capture Device doesn't work on versions over 2.8.2: the camera starts moving then freezes, crashes, sometimes goes erratic. It's too bad I have to downgrade to 2.8.2 because the latest features seem cool, but also because this version of the plugin makes OBS crash when I close it.

I know we are a few people experiencing the same issue but I can't find any solution.

**Comment by SoulwayStudios** [comment]
Im also experiencing this issue with an Insta360 Link. Im running 2.8.1 and it "works" although theres a couple of frames of render lag as it moves, which is annoying. Basically when i have a PTZ location set, and press play on it, the eye lights up on the action but never turns off, locking up obs as it tries to fire off the ptz command over and over again. a single "add" value sends the add command and shuts off perfectly. but the "settings" option breaks.

**Comment by exeldro** [comment]
I was able to replicate the issue with my insta 360 link and made multiple improvements to make it work better, a test version is available at the bottom of this page when logged in:
https://github.com/exeldro/obs-move-transition/actions/runs/8036494750
Please let me know if this version works for you.

**Comment by Megilla** [comment]
Nice, now my Insta360 Link are working again! Thank you very much for the test version!

**Comment by SoulwayStudios** [comment]
Initial tests show this seems to work without any stuttering or lockups. thankyou so much.

**Comment by adrienmenielle** [comment]
It works! Thanks so much you're the best.
