### ISSUE TITLE
Movement is off, when using nested Scenes or Groups

### ISSUE THREAD

**Issue by WongKit** [exeldro/obs-move-transition#202]
Hi,

when using scenes as sources or adding elements into a group, the move animation seems to get confused.
I believe, that the issue depends on the size of the parent container (Scene or Group).

Setting a transition override to none as explained [here](https://github.com/exeldro/obs-move-transition/issues/179#issuecomment-1780546016) did nothing in my case.

I attached a minimal sample video and scene.

https://github.com/exeldro/obs-move-transition/assets/2545383/66e202dd-7e74-449a-81ec-557b0bf32571

[scene-movetest.json](https://github.com/exeldro/obs-move-transition/files/15141668/scene-movetest.json)

If a group has the same size as the single element within the group, the animation plays back as expected. If it contains other elements increasing the size (or using a scene instead of a group), the shown behavior occurs.

**Comment by AuracleTech** [comment]
They have to be at the exact same nested position, so make a nest on the other one aswell
This <https://www.youtube.com/watch?v=DQNhV_bbXQ8> helped me

**Comment by WongKit** [comment]
Thank you for your reply.
I tried using Scene 1 as a nested scene and transition to Scene 2, but the transition is still wobbly. I stuck to the referenced video and checked all alignments and bounding boxes. They are the same for all elements (align up left + no bounding box).

**Comment by AuracleTech** [comment]
what you mean by wobbly, same as your current video shows?

**Comment by WongKit** [comment]
Yes, in my actual project, it moves like in the current video. However, I tried to set it up again in the minimal example and the move transition is correct, but plays back at double the speed. Basically, I can work with that. Thanks!

**Comment by exeldro** [comment]
To make more visible what is happening you can add a color source to the Include scene that has the same size as that scene.
It is moving the size from 300x100 to 1920x1080 and the top left position from 642, 434 to 0,0
![move](https://github.com/exeldro/obs-move-transition/assets/5457024/b3dc34a4-84f8-4110-a893-3a05360ce90e)
