### ISSUE TITLE
Scale to Outer Bounds Issue with Crop to Bounding Box when Move Transition with Zoom & Fade

### ISSUE THREAD

**Issue by chrisspiegl** [exeldro/obs-move-transition#214]
I've started to use the Move Transitions and found that when I use the "Scale to Outer Bounds", Bounding Box Alignment set to "Center" and "Crop to Bounds" on elements, and then transition between scenes, the crop appears to be flickering / snapping on and off during the transition. This makes the transition unusable and eratic.

I tried using "Stretch to Bounds", "Scale to Inner Bounds" and the same thing does not happen.

I tried a number of different other things (Scale to Outer Bounds with different Bounding Box Positioning). But there are many that appear to transition without the grop, and then at the end of the transition, the crop is applied.

Is this expected behavior or a bug?
Is there a way to fix it and still use "Scale to Outer Bounds"?

Best, Chris

**Comment by chrisspiegl** [comment]
I looked into the code and found that the "Crop to Outer Bounds" appears to only be active if the difference in cop is "significant enough"? Maybe that's the issue here? Shouldn't it be respected no matter how small the crop is?

https://github.com/exeldro/obs-move-transition/commit/a86154b9c9d771637809f5dc8f189b316775c4b3#diff-c36b5f68ab87ecc792639c59279cbbe8bf90a6173070046d6bee4b30ef983665R434

**Comment by exeldro** [comment]
I was able to replicate the issue and made a fix for it. You can download a test version from the bottom of this page:
https://github.com/exeldro/obs-move-transition/actions/runs/9466205336

**Comment by chrisspiegl** [comment]
I tested v3.0.1 and the build, and they appear to be working.
However, my scenes also changed significantly in the meantime. 🙈
In case this issue comes back, I'll let you know.
