### ISSUE TITLE
Freeze before starting Move transition with Luma

### ISSUE THREAD

**Issue by Warths** [exeldro/obs-move-transition#23]
Hello ! 
Thanks for your great work, i'm really enjoying your plugin!

I found an issue when using In, Out and Move Transition set as Luma wipe.

Depending on how many sources you have, it freezes the rendering for a certain amount of frames before the transition, then proceed to render the transition properly.

From my tests, with 7 sources on the source and 10 on the destination, it's loosing 6 frames 
When i discovered the issue and tried to fix it, i had around 30 sources on both, and i was loosing about 25 frames. I grouped everything together, which seems to reduce the issue. 

It doesn't appear to be an hardware overload issue, as both CPU and GPU were not even close to half their maximum

I'm sorry for not being able to provide more clear information about the issue. I'll be glad to help reproduce the issue.

For those who seeks a workaround : Uses fade transition instead of Luma wipe. Less fancy, but no more frame stutter

Thanks !

**Comment by exeldro** [comment]
Can you test if with [this build](https://github.com/exeldro/obs-move-transition/actions/runs/105351271) setting the option cache transitions helps?

**Comment by Warths** [comment]
It's solving the issue ! Congrats and thanks a lot
