### ISSUE TITLE
"Fade" no longer working in 3.1.0

### ISSUE THREAD

**Issue by RandomNerd1** [exeldro/obs-move-transition#233]
The "fade" selection doesn't seem to work anymore for appearing/disappearing items, instead things set to "fade" 'pop' in and out (shrinking into or expanding from a single point). Anyone else experiencing this?

This is how I have it set up: https://i.imgur.com/kQFxEof.png

**Comment by exeldro** [comment]
Zoom became a float slider instead of a bool, looks like the automatic conversion is not working as expected

**Comment by exeldro** [comment]
Can you test if this build fixes it for you?
https://github.com/exeldro/obs-move-transition/actions/runs/11138487116
Downloads should be at the bottom of that page when logged in on GitHub.

**Comment by RandomNerd1** [comment]
Doesn't seem to fix it, no. I do see that appearing/disappearing items do fade in/out, but they're also 'zooming' in/out at the same time, I can't get the elements to stay the same size, and in the same position, during the fade, even when position is set to "none".

I managed to record a short video, where you can see even in the "preview transition" that the behavior seems not to be correct. Why does A shrink away and B 'grow' in as the transition happens? I don't think any of the settings I set should cause this. I changed the duration to 2000 ms so it would be clearer to see: https://streamable.com/6x9qk8

**Comment by exeldro** [comment]
Zoom is set to 0% in both, it should be 100% when you want no zooming

**Comment by RandomNerd1** [comment]
I do not remember ever touching that setting...and now it just clicked what you meant by this earlier!

> Zoom became a float slider instead of a bool, looks like the automatic conversion is not working as expected

I thought you were talking about "zoom" as in something the plugin does, not a literal setting called "Zoom"! Now of course, I understand that it's a slider, and must not have been before (I don't remember what it looked like previously). Sorry for not realizing!

In that case, yes, setting zoom to 100% immediately restored the behavior to what I expected, though I already installed that new build, so I can't confirm that the same works in 3.1.0.

Thanks so much!
