### ISSUE TITLE
OBS Crashes on close with plugin version 3.1.0

### ISSUE THREAD

**Issue by PixelFox3** [exeldro/obs-move-transition#235]
Today I updated from 3.0.2 to 3.1.0 and i started to get a crash error every time i closed OBS.
also sometimes my OBS just stopped working and i had to force close it with the system manager. But since I was testing the window dock plugind and doing a lot of other things, so maybe those crashes were not related.

But the close-crash is. I rolled back to 2.0.3 an im not getting the crash error anymore. 
i attach one of the many crash logs it generated while testing what could be the cause

Windows 11
i9-13980HX
RTX 4090

[Crash 2024-10-07 04-34-23.txt](https://github.com/user-attachments/files/17272092/Crash.2024-10-07.04-34-23.txt)

**Comment by exeldro** [comment]
Can you try if this build fixes it for you?
https://github.com/exeldro/obs-move-transition/actions/runs/11144419652
The download should be at the bottom of the page when logged in on GitHub.

**Comment by PixelFox3** [comment]
it solves the issue. 👍
