### ISSUE TITLE
Missing translation in 1.4.0

### ISSUE THREAD

**Issue by COOLIGUAY** [exeldro/obs-move-transition#28]
In the new "Next Move" option, "None" will not be translated in other languages.

https://github.com/exeldro/obs-move-transition/blob/7259b9e26c577bca73cd1d77c61c994f8103029a/move-source-filter.c#L386

https://github.com/exeldro/obs-move-transition/blob/7259b9e26c577bca73cd1d77c61c994f8103029a/data/locale/en-US.ini#L74

**Comment by exeldro** [comment]
Fixed in 1.5.0
