### ISSUE TITLE
Positioning error bug

### ISSUE THREAD

**Issue by Bmille916** [exeldro/obs-move-transition#40]
I seem to have found a positioning bug where the more times i show and hide the source, the closer it moves. So i have my source off screen, and like i said eventually i can move it enough times to where it ends up showing onscreen after a move when it is supposed to be off screen.

Edit: also the toggle doesn't seem to be working properly.

**Comment by exeldro** [comment]
Are you using the move source filter with relative move enabled? Moving to a absolute position should always give the same results.

What is the expected behavior for toggle and what is the behavior you are getting?

**Comment by Bmille916** [comment]
Relative move is unticked. Continues to shift a slight bit after every move.
For toggle, i assumed i would hide the vlc source offscreen. Then, when moving it with a hotkey it would show. And then when reversing it, it should hide again. Currently, it hide just fine, but when i go to move onscreen, it shows then hides again.

**Comment by exeldro** [comment]
@Bmille916 can you test if the bug is still there with version 1.7.8?
