### ISSUE TITLE
"Next Move: Reverse" on Hotkey breaks when the hotkey is pressed again before the transition is complete

### ISSUE THREAD

**Issue by Schogol** [exeldro/obs-move-transition#42]
Reprosteps:
1. Set up an Effect filter which moves a Source from A to B
2. Set "Next Move" to Reverse and "Next Move On" to Hotkey
3. Set up a hotkey to use
4. Press your hotkey to move your source from A to B and hit the hotkey again before the source has reached its destination

The source will only reverse to the position in which you pressed the hotkey and will not return to its origin.

Video:
https://streamable.com/4d6vpn

**Comment by Schogol** [comment]
Might be related to #40 ?

**Comment by exeldro** [comment]
Version 1.7.8 should fix it, can you verify if it works for you?

**Comment by Schogol** [comment]
Can confirm, 1.7.8 fixes the issue. great job
