### ISSUE TITLE
Recursive Move Value filter crashes OBS

### ISSUE THREAD

**Issue by orion78fr** [exeldro/obs-move-transition#49]
Step to reproduce :

- Add a Move Value filter to a Source
- In filter, chose the Move Value filter itself
- OBS crashes

Even though the crash is easily fixable with an if check, I think the current filter should not be selectable, it has no sense to animate yourself. I don't know if it makes sense to move a value of another move value filter though.

**Comment by exeldro** [comment]
What version did you get that crash with? It looks like the bug I fixed in version 2.0.1

**Comment by orion78fr** [comment]
Oh ! I probably got 1.7.1 by accident because the lastest releases aren't published on github. So yeah OBS doesn't crash now.
