### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by starcraft66** [exeldro/obs-move-transition#51]
Hello, I am packaging this plugin for use on NixOS and I need a clarification for what license this project is licensed under. The github repo says it is under the GPL-2.0 License but I need to know specifically if it is licensed under GPL-2.0 only or GPL-2.0+ (GPLv2 or any later version of the GPL).

**Comment by exeldro** [comment]
I'm not a license expert, so I choose the same license as  the OBS studio project. I see they have "General Public License v2 (or any later version) " in the readme. You need me to state that somewhere?

**Comment by starcraft66** [comment]
That's good enough for me!
