### ISSUE TITLE
Consider tagging releases on GitHub again

### ISSUE THREAD

**Issue by starcraft66** [exeldro/obs-move-transition#52]
Hello, I am packaging this plugin for use on NixOS and I noticed you stopped tagging your releases on GitHub some time ago. It would be pretty useful if you kept your GitHub tags up to date with the versions you publish on the OBS plugins page as it would facilitate pinning versions of your repository for anyone else packaging this plugin for another distribution.

**Comment by exeldro** [comment]
added tags and releases for 2.0.0, 2.0.1 and 2.0.2
