### ISSUE TITLE
Audio move filter can’t interact with integer filter settings

### ISSUE THREAD

**Issue by WouterJanson** [exeldro/obs-move-transition#57]
Currently the audio move filter isn’t able to interact with filter settings that take an integer value, such as the opacity on an colour correction filter.

This is however available in the 'normal' move filter.

**Comment by exeldro** [comment]
That should be added since version 2.2.1, is that the version you are seeing it in?

**Comment by WouterJanson** [comment]
Wow, didn’t even realise you already released a new version. I’ll check it out tonight, in that case this issue is redundant.
