### ISSUE TITLE
Could you teach us how to do it?

### ISSUE THREAD

**Issue by iesvme** [exeldro/obs-move-transition#58]
![3](https://user-images.githubusercontent.com/16969250/103408029-ce6a0200-4b9b-11eb-8d71-1e6dae6a4e17.gif)

It's so cool!
The size of camera will gradually enlarged！but how to do it?

Sorry, sir, I upload your photo.

**Comment by exeldro** [comment]
That is a video from Andilippi, to be sure how he has done it you should ask him. As far as I know he answers every single comment on his videos, so just leave a comment on the video with your question. Or go to his discord and ask it there.

You can crop a source in OBS by keep alt pressed while dragging a handle of the source.
Have 1 scene with a cropped version of your webcam and 1 scene with a full webcam and do a source transition between them.
Or if you want to do it in 1 single scene you can use move source filters on the scene to move between the 2 different tranforms.

**Comment by iesvme** [comment]
Thank you for your a good answer!
