### ISSUE TITLE
Sometimes it will be failed when using studio mode.

### ISSUE THREAD

**Issue by iesvme** [exeldro/obs-move-transition#59]
Sometimes it will be failed when using studio mode.
OBS: 26.1
Move: 2.2.1

**Comment by exeldro** [comment]
Huge part of the problem will be fixed if [this PR ](https://github.com/obsproject/obs-studio/pull/3819) gets accepted into OBS.

**Comment by iesvme** [comment]
Oh, I get it. thank you so much.

Exeldro <notifications@github.com> 于 2021年1月2日周六 19:26写道：
