### ISSUE TITLE
Make Image Source Rotate?

### ISSUE THREAD

**Issue by Velkas** [exeldro/obs-move-transition#65]
I was recommended this plugin but not recommended how to set this up--

How can I get an image source in a scene rotate while it's visible? I just want it to slowly rotate like a disc or vinyl viewed straight on.

**Comment by exeldro** [comment]
Right click the image go to edit transform, set alignment to center and change the rotation.
If you want it to keep spinning you make a move source to move the rotation from 0 to 360 over a long time and have a next move that resets the rotation to 0 in 10ms and as next move has the moving from 0 to 360

**Comment by Velkas** [comment]
That worked! Thank you so much. Took a bit to connect the dots but now that I understand it, it makes perfect sense. Appreciate the help!
