### ISSUE TITLE
Memory usage increases

### ISSUE THREAD

**Issue by COOLIGUAY** [exeldro/obs-move-transition#8]
First of all, thank you for this amazing plugin!

I think i found a memory issue.

In a scene collection with multiple images and transitioning with move-transition many times, the memory usage increases.

The only way i found to isolate the issue has been:

1. Create a new scene collection
2. Add a image bigger than 1920*1080
3. Set Transform/Fit to screen
4. Set Scale Filtering to Bilinear
5. Add a new scene
6. Add another different image, it doesn't matter what resolution it is
7. Add the move transition
8. Transition between the 2 scenes several times with move-transition

With only two images it takes longer to get this issue (2 minutes transitioning again and again)
In the scene collection i use, having many more images happens earlier.

With images in 1080p the issue happens too, but i couldn't find an easy way to reproduce it.
The only common factor i find is the scale filter and resize the image.

OBS Studio 25.0.4
Move-transition 1.0.0
Windows 10 1903
2 displays at 1920*1080 60hz
i7 6700K
GTX 1080

I have used these images for this example:
https://images.app.goo.gl/zsp5qDhbuBm23qsV9
https://images.app.goo.gl/yXUfTTL9HWqRMBEz9

Memory usage:
![2020 04 12 00 16 28](https://user-images.githubusercontent.com/55640387/79056314-521e4000-7c55-11ea-8e98-7888f9512993.gif)

**Comment by exeldro** [comment]
It looks like signalling the transition stopped fixed a memory leak on my system. Can you check if version 1.0.1 fixes the issue for you?

**Comment by COOLIGUAY** [comment]
I have been transitioning for more than half an hour in 2 different scene collections and it works fine, perfectly fixed!
