### ISSUE TITLE
obs-move-transition on Debian

### ISSUE THREAD

**Issue by eribertomota** [exeldro/obs-move-transition#89]
Hi @exeldro,

Thanks a lot for your nice work. My name is Eriberto and I am a Debian Developer. This "issue" is to talk to you that I sent obs-move-transition to Debian. On some days it will be available for users.

Is not possible build a plugin inside OBS in Debian. This build must be alone. I made some changes (via patches in build time) to allow move-transition build alone. My git repository for packaging is temporarily here[1]. After the package is accepted in Debian, the new repository will be this[2].

[1] https://salsa.debian.org/eriberto/obs-move-transition
[2] https://salsa.debian.org/debian/obs-move-transition

All procedures to package the plugin are in the debian/ directory (at [1]). There are patches in debian/patches/. I would like to ask if you could solve in your code some changes made via patches? If not, no problems; in this case, I will remain using the patches. In obs-scene-switcher[3][4], the mainstream (upstream for Debian) added a new option for me (-DBUILD_OUT_OF_TREE=1) to allow build alone on Debian. On Debian I use the libobs-dev to build. The libobs-dev provides headers in /usr/include/obs/, but the includes in the file obs-frontend-api.h is pointing to /usr/include/. I already opened a bug about this in Debian and it will be fixed. I am waiting a decision from the maintainer of the libobs-dev in Debian about the possibility of the provide the file plugins/obs-transitions/easings.h via libobs-dev. If not, I will need to copy this file from each new version of the OBS and this is very complicated for some reasons.

[3] https://github.com/WarmUpTill/SceneSwitcher

Another problem is the file version.h, not removed before a new build. After a first build, when trying build twice, Debian considers that source code was modified and stops to build unless the file be removed.

The project says that move transition is compatible with OBS 25+. However, I was able to build it over OBS 27 only. Is there a way to make it compatible with OBS 25/26? If needed, I can send a PR simulating a Debian packaging via CI for GitHub, to help you identify points of breaks.

Thanks a lot for your attention. You can see the package in the Debian input queue here[4].

[4] https://ftp-master.debian.org/new.html

Regards,

Eriberto

**Comment by exeldro** [comment]
@eribertomota, thank you for making my plugin available on Debian.
I looked at the patches you used and can't apply them without breaking my current GitHub Actions builds. Can you create pull requests with the changes you want that keep my GitHub Actions builds working?
Version 2.5.0 of the move transition plugin only works with OBS version 27 or higher. On the OBS forum I can not set a required version per version of the plugin.

**Comment by eribertomota** [comment]
Hi @exeldro,

I know well autotools but I have no experience with CMake. I solved the issues in CmakeList.txt but I think that some changes in source code are needed to make all things work automatically. Consequently, I will keep the patches in Debian and move-transition will work. I won't send my changes in CmakeList.txt because not worth it.

Thanks for your attention.

Regards,

Eriberto
